import React from "react";
import { ScrollView, Text, StyleSheet } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

export default function TermsOfServiceScreen() {
  return (
    <SafeAreaView style={styles.safe} edges={["top", "bottom"]}>
      <ScrollView contentContainerStyle={styles.container}>
        <Text style={styles.title}>Terms of Service</Text>

        <Text style={styles.text}>
          By using the NOFARI application, you agree to the following Terms of
          Service.
        </Text>

        <Text style={styles.section}>Purpose of NOFARI</Text>
        <Text style={styles.text}>
          NOFARI is an AI-powered conversational assistant designed to provide
          supportive dialogue and informational responses.
        </Text>

        <Text style={styles.section}>AI Disclaimer</Text>
        <Text style={styles.text}>
          Responses generated by NOFARI are produced by artificial intelligence
          and may not always be accurate or appropriate for every situation.
        </Text>

        <Text style={styles.section}>No Emergency Use</Text>
        <Text style={styles.text}>
          NOFARI is not intended for emergency situations. If you are in danger
          contact local emergency services immediately.
        </Text>

        <Text style={styles.section}>User Responsibility</Text>
        <Text style={styles.text}>
          You are responsible for how you use NOFARI and for any information you
          choose to share within the app.
        </Text>

        <Text style={styles.section}>Service Availability</Text>
        <Text style={styles.text}>
          NOFARI is provided on an “as is” and “as available” basis.
        </Text>

        <Text style={styles.section}>Limitation of Liability</Text>
        <Text style={styles.text}>
          NOFARI and its operators are not liable for any damages or losses
          resulting from use of the app.
        </Text>

        <Text style={styles.section}>Contact</Text>
        <Text style={styles.email}>contact@nofameai.com</Text>

        <Text style={styles.footer}>
          Last Updated: December 1, 2025
        </Text>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#020925" },
  container: { padding: 20, paddingBottom: 40 },
  title: {
    color: "#ffffff",
    fontSize: 26,
    fontWeight: "800",
    marginBottom: 16,
  },
  section: {
    color: "#d6b24a",
    fontSize: 18,
    fontWeight: "700",
    marginTop: 20,
    marginBottom: 8,
  },
  text: {
    color: "#e6e6e6",
    fontSize: 15,
    lineHeight: 22,
  },
  email: {
    color: "#00ffc6",
    fontSize: 16,
    marginTop: 6,
    fontWeight: "600",
  },
  footer: {
    marginTop: 30,
    color: "#8a8a8a",
    fontSize: 13,
  },
});